### ISSUE TITLE
Support for building specific revision?

### ISSUE THREAD

**Issue by vaijab** [jszwedko/go-circleci#26]
@jszwedko looks like https://circleci.com/docs/api/v1-reference/#new-build supports building a specific revision or tag. Do you have plans to support it? If so, would you be happy if contribute a patch, such as:

```golang
func (c *Client) Build(account, repo, branch, revision, tag string) (*Build, error) {
    ....
}
```

This will be a breaking change, unless you want me to introduce a new method?

**Comment by jszwedko** [comment]
@vaijab apologies for the severe delay; I lost track of this issue. @vieux added a flexible trapdoor in #34 to specify arbitrary parameters. Would this work for your use case?

**Comment by vaijab** [comment]
@jszwedko that looks great. I will migrate away from my fork as soon as I find some time and will let you know of any issues. I doubt there will be any. Thanks @vieux too.
