### ISSUE TITLE
missing API info

### ISSUE THREAD

**Issue by jedi4ever** [jszwedko/go-circleci#3]
Hi @jszwedko ,

 I've just found your work . Nice! I've also found https://github.com/mtchavez/circleci
They have done a lot of work at finding the 'missing/undocumented' api calls such as listing envvars. If I have time I'll help to add some. Meanwhile this ticket was to give you some inspiration.

**Comment by jedi4ever** [comment]
never mind, I mistakingly though you had only implemented the functions of circleci-cli
good job

**Comment by jszwedko** [comment]
@jedi4ever thank you! Please feel free to file issues for any missing endpoints.
