### ISSUE TITLE
Support for triggering builds by project

### ISSUE THREAD

**Issue by lexiross** [jszwedko/go-circleci#35]
Hi there! There's a new API that's still in beta for triggering builds: https://circleci.com/docs/api/v1-reference/#new-project-build The old trigger build API is not compatible with Circle 2.1, so this new API is the only way to trigger builds for those on the new version.

I'm happy to take this on - are you accepting PRs? Thanks!

**Comment by jszwedko** [comment]
Resolved by https://github.com/jszwedko/go-circleci/pull/39
