### ISSUE TITLE
[Improvement] "You must log in first" error message should tell you how to login

### ISSUE THREAD

**Issue by coilysiren** [jszwedko/go-circleci#38]
## What Happpened

I called an api endpoint like so (psuedo-code)

```golang
circleci.Client{Token: circleToken}.ListProjects()
```

and got this error message

> 401: You must log in first

## What I Was Expecting

When I call an api endpoint without being authorized, I get an error message like this

> 401: You must log in first. You can log in via ...

**Comment by coilysiren** [comment]
To followup:

- this was definitely user error on my part 😭
- and the error should still be better
- but since its piped straight back from CircleCI's api, it should be changed in the API (not this package). I'll make in issue there 🏃‍♀

**Comment by jszwedko** [comment]
:+1: thanks for the thoughts! I agree that given this library is just a light wrapper around the API, I would hesitate to modify Circle's response, but I welcome additional ideas to make this error clearer and easier to handle by users of the library.

Right now, you can look for an `APIError` with a `StatusCode` of `401` to identify unauthorized errors.

**Comment by coilysiren** [comment]
Yeah I think I'm gonna look for 401 and print the messages my coworkers would be expecting (eg. "Invalid API key" or similar)

Thanks for checking in ^_^!
