### ISSUE TITLE
Error parsing 429 response

### ISSUE THREAD

**Issue by graza-io** [jszwedko/go-circleci#43]
## Context

When the error received is a `429` (Rate-Limited) the response body doesn't appear to be `json` and as such we receive an error:

```
Error: 429: unable to parse API response: invalid character 'R' looking for beginning of value
```

This stems from [this code](https://github.com/jszwedko/go-circleci/blob/v0.3.0/circleci.go#L152-L162) where all responses with a code >= 300 are having their body parsed through the `json.Unmarshal` function.

**Comment by jszwedko** [comment]
Ah, good catch. Happy to accept a PR here.

**Comment by graza-io** [comment]
Sure thing, this gives back a more useful error to the user: https://github.com/jszwedko/go-circleci/pull/44
