### ISSUE TITLE
Release of latest code?

### ISSUE THREAD

**Issue by graza-io** [jszwedko/go-circleci#45]
@jszwedko, recently code was merged into `master` to support handling the Rate-Limit response not being JSON, would it be possible to cut a release with this change? (Maybe `0.3.1`?)

**Comment by ParthaI** [comment]
Hello @jszwedko, Is there any ETA to  release a new version with the fixes: https://github.com/jszwedko/go-circleci/pull/44?

**Comment by jszwedko** [comment]
Thanks for the bump @ParthaI . I last track of this issue. I just pushed v0.4.0 now. Let me know if you have any issues!
