### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by stevenjack** [jszwedko/go-circleci#9]
Hey there!

Great work on the library, we're using it in one of our projects and it would be great if you tagged the repo so we had a version number when adding the package as a dep in our app!

**Comment by jszwedko** [comment]
:+1: agreed, I think it is time.

**Comment by jszwedko** [comment]
I'll tag after we get #10 merged in

**Comment by jszwedko** [comment]
Apologies, track of this, but finally tagged two initial versions since I merged a backwards incompatible change (#20).

Please feel free to pin to `v0.1.0` or `v0.2.0`! I might tag a `v1.0.0` soon as well.
